## #############################################################################
## Continuous Integration for Static Site
## #############################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: CI for Static Site

## #############################################################################
## Parameters
## #############################################################################

Parameters:
  ArtifactBucketName:
    Type: String
    Description: name of the artifact bucket 
    Default: com.diguisepperecipes.artifacts

  GithubRepositoryName:
    Type: String
    Description: the github repo
    Default: diguisepperecipes.com

  GithubUserName:
    Type: String
    Description: the github account name
    Default: jwc2790

  CodeBuildProjectName:
    Type: String
    Description: codebuild project name
    Default: diguiseppe-recipes

  StackName:
    Type: String
    Description: stack name
    Default: diguiseppe-recipes-test

  GithubOAuthToken:
    Type: String
    Description: Create a token with 'repo' and 'admin:repo_hook' permissions here https://github.com/settings/tokens
    Default: 193dd78376eb09b21f23df911e553086667a642c

## #############################################################################
## Resources
## #############################################################################

Resources:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  SiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: 
        Ref: ArtifactBucketName

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Sub: CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - codebuild.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        -
          PolicyName: CodeBuildAccessPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  # - logs:CreateLogGroup
                  # - logs:CreateLogStream
                  # - logs:PutLogEvents
                  # - s3:*
                  # - cloudfront:*
                  - '*'
                Resource:
                  # - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
                  - '*'

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      BadgeEnabled: true
      Name: 
        Ref: CodeBuildProjectName
      ServiceRole: 
        Fn::GetAtt: CodeBuildServiceRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0
      Source:
        Auth:
          Type: OAUTH
        Location: 
          Fn::Sub: "https://github.com/${GithubUserName}/${GithubRepositoryName}.git"
        Type: GITHUB
      Triggers:
        Webhook: true
      TimeoutInMinutes: 10

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Sub: CodePipelineRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        -
          PolicyName: CodePipelineAccessPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:* 
                  - cloudformation:* 
                  - codebuild:* 
                  - codedeploy:*
                  - iam:*
                Resource:
                  # - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codepipeline/*
                  - '*'

  # CloudformationServiceRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #       - Action:
  #         - sts:AssumeRole
  #         Effect: Allow
  #         Principal:
  #           Service:
  #           - cloudformation.amazonaws.com
  #       Version: '2012-10-17'
  #     Path: "/"
  #     Policies:
  #       - PolicyName: DeployCloudformationStack
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #           - Resource: "*"
  #             Effect: Allow
  #             Action:
  #             - "*" 

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  AppPipeline: 
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      RoleArn: 
        Fn::GetAtt: CodePipelineServiceRole.Arn
      Stages: 
        - Name: Source
          Actions: 
            - Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - Name: SourceOutput
              Configuration:
                Owner:
                  Ref: GithubUserName 
                Repo: 
                  Ref: GithubRepositoryName
                Branch: master
                OAuthToken:
                  Ref: GithubOAuthToken
              RunOrder: 1
              

        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                  - Name: SourceOutput
              ActionTypeId: 
                  Category: Build
                  Owner: AWS
                  Version: 1
                  Provider: CodeBuild
              OutputArtifacts:
                  - Name: BuildOutput
              Configuration: 
                  ProjectName: 
                    Ref: CodeBuildProject

        - Name: Infrastructure
          Actions:
            - Name: Infrastructure
              InputArtifacts:
                  - Name: BuildOutput
              ActionTypeId: 
                  Category: Deploy
                  Owner: AWS
                  Version: 1
                  Provider: CloudFormation
              OutputArtifacts:
                  - Name: InfrastructureOutput
              Configuration: 
                ActionMode: REPLACE_ON_FAILURE
                RoleArn:
                  Fn::GetAtt: CodeBuildServiceRole.Arn
                Capabilities: CAPABILITY_NAMED_IAM
                StackName:
                  Ref: StackName
                TemplatePath: BuildOutput::build/template.yml

        # TODO:  Create CloudFront invalidation. (likely in a codebuild step)
              
      ArtifactStore: 
        Type: S3
        Location: 
          Ref: ArtifactBucketName
      
      # DisableInboundStageTransitions: 
      #   - 
      #     StageName: Release
      #     Reason: "Disabling the transition until integration tests are completed"


## #############################################################################
## Outputs
## #############################################################################

# Outputs:

#     RecipeServiceApiGatewayArn:
#         Description: Recipe Lambda Function ARN
#         Value: 
#             Fn::Sub: >-
#                 arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RecipeServiceLambda.Arn}/invocations
#         Export:
#             Name: RecipeServiceApiGatewayArn